<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>true</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
	<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.10" />
	<PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
  </ItemGroup>

</Project>
